<fieldset class="fieldset file-upload">
    <div class="field customer_file_upload">
        <label for="customer_avatar" class="label"><span><?php /* @escapeNotVerified */
                echo 'Anh' ?></span></label>
        <div class="control">
            <input type="file" name="customer_avatar" id="customer_avatar" title="<?php /* @escapeNotVerified */
            echo __('Custom Image') ?>" class="input-text" data-validate="{required:false}">
        </div>
    </div>
</<fieldset>
