<?php
/**
 * @var $block \Magenest\Knockout\Block\ModalOverlay
 */
$content = $block->getContent();
?>
<div id="modal-content" display="none">
    <div class="modal-inner-content">
        <h2>Modal Title</h2>
        <?= $content ?>
    </div>
</div>

<script>
    require(
        [
            'jquery',
            'Magento_Ui/js/modal/modal'
        ],
        function($, modal) {
            var options = {
                type: 'popup',
                responsive: true,
                innerScroll: true,
                title: 'Pop-up title',
                buttons: [{
                    text: $.mage.__('Close'),
                    class: 'modal-close',
                    click: function (){
                        this.closeModal();
                    }
                }]
            };

            modal(options, $('#modal-content'));
            $(document).ready(function() {
                $("#modal-content").modal("openModal");
            });
        }
    );
</script>
